# Generated by Django 3.0.10 on 2021-08-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communc',
            new_name='Communce',
        ),
    ]
