# Generated by Django 3.0.10 on 2021-08-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='user_id',
        ),
    ]
