# Generated by Django 3.0.10 on 2021-08-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210823_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communce',
            name='district',
        ),
        migrations.RemoveField(
            model_name='provice',
            name='commnuce',
        ),
        migrations.AddField(
            model_name='communce',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provice',
            name='country_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='communce',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='communce',
            name='communce_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='village',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provice',
            name='province_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='communce',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='district',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jobs',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nationality',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='organization',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='province',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_profile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='village',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Pro_shortName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
