# Generated by Django 3.0.10 on 2021-08-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210824_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='village',
            new_name='communce',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='communce',
            new_name='district',
        ),
    ]
