# Generated by Django 3.0.10 on 2021-08-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210824_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_profile',
            new_name='profile_id',
        ),
    ]
