# Generated by Django 3.0.10 on 2021-08-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_communce_countries_district_provice_userinfo_userprofile_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=250, null=True)),
                ('orderBy', models.CharField(max_length=250, null=True)),
                ('inputer', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('createDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=250, null=True)),
                ('userID', models.CharField(max_length=250, null=True)),
                ('actionType', models.CharField(max_length=250, null=True)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCode', models.CharField(max_length=250, null=True)),
                ('categoryID', models.CharField(max_length=250, null=True)),
                ('bookTitle', models.CharField(max_length=250, null=True)),
                ('dateIn', models.DateTimeField()),
                ('inputer', models.CharField(max_length=250, null=True)),
                ('releaseYear', models.CharField(max_length=250, null=True)),
                ('page', models.CharField(max_length=250, null=True)),
                ('cost', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('quentity', models.CharField(max_length=250, null=True)),
                ('isbn', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('pdf', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lateChCost', models.CharField(max_length=250, null=True)),
                ('dates', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=250, null=True)),
                ('visitType', models.CharField(max_length=250, null=True)),
                ('visitDateTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='communce',
            name='communceName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='communce',
            name='province',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='CountryName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='countryConde',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='communce',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='districtName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='provice',
            name='country_code',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='provice',
            name='provinceName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='communce',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='district',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jobs',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nationality',
            field=models.CharField(max_length=1250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='organization',
            field=models.CharField(max_length=1250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='proID',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='province',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userID',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='village',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ProShort',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='createdBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='villageName',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
