# Generated by Django 3.0.10 on 2021-08-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210831_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provice',
            old_name='country_code',
            new_name='countryCode',
        ),
    ]
